# Generated by Django 4.1.3 on 2023-01-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pro_desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='pro_title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
